### PR TITLE
added Rust inference example

### PR DESCRIPTION
**Pull request by filipw**
## Purpose

Introduces an example of doing cross-platform, high performance inference with Rust.

## Does this introduce a breaking change?

When developers merge from main and run the server, azd up, or azd deploy, will this produce an error?
If you're not sure, try it out on an old environment.

```
[ ] Yes
[x] No
```

## Does this require changes to learn.microsoft.com docs?

This repository is referenced by (https://azure.microsoft.com/products/phi-3)
which includes deployment, settings and usage instructions.

```
[ ] Yes
[x] No
```

## Type of change

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Documentation content changes
[ ] Other... Please describe:
```

I only included the documentation/tutorial, but if desired, I may also commit the sample code.

### CODE REVIEW

**Comment by leestott** [comment]
@filipw sorry there a broken link in your docs https://github.com/huggingface/candle/tree/main/candle-examples/examples/quantized-phi3 is not valid link.

**Comment by filipw** [comment]
Thanks for catching this - fixed!

**Comment by skytin1004** [comment]
Hi @filipw, Great work on the Rust inference example documentation!
I noticed that there is still a broken link in the file `./md/01.Introduce/Edgeandcloud.md` pointing to `https://aka.ms/try-phi3-hf-chat`. It would be ideal to replace the `aka.ms` short URL with the original full URL. Could you please update this link to the correct URL?

**Comment by skytin1004** [comment]
I noticed that there is still a broken link in the file `./md/01.Introduce/Edgeandcloud.md`. I replaced the aka.ms short URL with the original full URL in #77 .

**Pull request merged**
